<?php

// GENERATED from food-icon-manifest.json by scripts/gen-food-icons.mjs - do not edit by hand.
// PHP mirror of packages/core/src/food-icons.generated.ts's EXTRA_ICON_ENTRIES - see
// App\Support\FoodIconMatcher for the curated (hand-tuned, non-generated) 10 entries.

namespace App\Support;

class FoodIconKeywords
{
    public const EXTRA = [
        'icon1' => ['keywords' => ['fish', 'fillet'], 'nutrition_category' => 'protein'],
        'icon2' => ['keywords' => ['tuna'], 'nutrition_category' => 'protein'],
        'icon3' => ['keywords' => ['salmon', 'sashimi'], 'nutrition_category' => 'protein'],
        'icon4' => ['keywords' => ['sushi'], 'nutrition_category' => 'other_extras'],
        'icon5' => ['keywords' => ['sour', 'cream'], 'nutrition_category' => 'dairy'],
        'icon6' => ['keywords' => ['rice', 'porridge'], 'nutrition_category' => 'grains'],
        'icon8' => ['keywords' => ['tomato', 'soup'], 'nutrition_category' => 'vegetables'],
        'icon9' => ['keywords' => ['fish', 'bunggeopang'], 'nutrition_category' => 'protein'],
        'icon10' => ['keywords' => ['ramen'], 'nutrition_category' => 'other_extras'],
        'icon11' => ['keywords' => ['pizza'], 'nutrition_category' => 'other_extras'],
        'icon12' => ['keywords' => ['raw', 'steak', 'beef', 'meat'], 'nutrition_category' => 'protein'],
        'icon13' => ['keywords' => ['cooked', 'steak', 'grilled', 'beef'], 'nutrition_category' => 'protein'],
        'icon14' => ['keywords' => ['raw', 'chicken'], 'nutrition_category' => 'protein'],
        'icon16' => ['keywords' => ['pickle'], 'nutrition_category' => 'other_extras'],
        'icon18' => ['keywords' => ['popcorn'], 'nutrition_category' => 'vegetables'],
        'icon19' => ['keywords' => ['egg'], 'nutrition_category' => 'protein'],
        'icon20' => ['keywords' => ['drumstick', 'chicken', 'leg', 'wings'], 'nutrition_category' => 'protein'],
        'icon21' => ['keywords' => ['pancakes'], 'nutrition_category' => 'grains'],
        'icon22' => ['keywords' => ['taco'], 'nutrition_category' => 'other_extras'],
        'icon23' => ['keywords' => ['raw', 'whole', 'chicken', 'turkey'], 'nutrition_category' => 'protein'],
        'icon24' => ['keywords' => ['cooked', 'grilled', 'chicken', 'turkey'], 'nutrition_category' => 'protein'],
        'icon25' => ['keywords' => ['dumpling', 'wrap'], 'nutrition_category' => 'protein'],
        'icon27' => ['keywords' => ['egg'], 'nutrition_category' => 'protein'],
        'icon28' => ['keywords' => ['boiled', 'egg'], 'nutrition_category' => 'protein'],
        'icon29' => ['keywords' => ['hotdog', 'bun'], 'nutrition_category' => 'grains'],
        'icon30' => ['keywords' => ['kebab', 'taco', 'tortilla', 'wrap'], 'nutrition_category' => 'grains'],
        'icon31' => ['keywords' => ['kebab', 'skewer', 'meat', 'stick', 'satay'], 'nutrition_category' => 'protein'],
        'icon32' => ['keywords' => ['sushi'], 'nutrition_category' => 'other_extras'],
        'icon33' => ['keywords' => ['teriyaki', 'chicken', 'rice'], 'nutrition_category' => 'protein'],
        'icon34' => ['keywords' => ['bread'], 'nutrition_category' => 'grains'],
        'icon35' => ['keywords' => ['wheat', 'stalk'], 'nutrition_category' => 'grains'],
        'icon36' => ['keywords' => ['meat'], 'nutrition_category' => 'protein'],
        'icon37' => ['keywords' => ['rice', 'ball'], 'nutrition_category' => 'grains'],
        'icon38' => ['keywords' => ['rice', 'grain'], 'nutrition_category' => 'grains'],
        'icon39' => ['keywords' => ['burger', 'sandwiches'], 'nutrition_category' => 'other_extras'],
        'icon40' => ['keywords' => ['rice', 'ball', 'onigiri'], 'nutrition_category' => 'grains'],
        'icon41' => ['keywords' => ['sausage', 'bun', 'hotdog'], 'nutrition_category' => 'protein'],
        'icon42' => ['keywords' => ['bacon'], 'nutrition_category' => 'protein'],
        'icon43' => ['keywords' => ['mushroom'], 'nutrition_category' => 'vegetables'],
        'icon44' => ['keywords' => ['wine', 'bottle'], 'nutrition_category' => 'other_extras'],
        'icon45' => ['keywords' => ['oat'], 'nutrition_category' => 'grains'],
        'icon46' => ['keywords' => ['cauliflower'], 'nutrition_category' => 'vegetables'],
        'icon47' => ['keywords' => ['sausage'], 'nutrition_category' => 'protein'],
        'icon48' => ['keywords' => ['berry'], 'nutrition_category' => 'fruit'],
        'icon49' => ['keywords' => ['tomato', 'sauce'], 'nutrition_category' => 'vegetables'],
        'icon50' => ['keywords' => ['double', 'burger', 'stack'], 'nutrition_category' => 'other_extras'],
        'icon51' => ['keywords' => ['burger'], 'nutrition_category' => 'other_extras'],
        'icon52' => ['keywords' => ['rolled', 'wrap'], 'nutrition_category' => 'grains'],
        'icon53' => ['keywords' => ['salad'], 'nutrition_category' => 'other_extras'],
        'icon54' => ['keywords' => ['tomato'], 'nutrition_category' => 'vegetables'],
        'icon55' => ['keywords' => ['raddish'], 'nutrition_category' => 'other_extras'],
        'icon56' => ['keywords' => ['broccoli'], 'nutrition_category' => 'vegetables'],
        'icon57' => ['keywords' => ['bamboo', 'sugarcane'], 'nutrition_category' => 'other_extras'],
        'icon58' => ['keywords' => ['capcicum', 'bell', 'pepper'], 'nutrition_category' => 'other_extras'],
        'icon59' => ['keywords' => ['avocado'], 'nutrition_category' => 'other_extras'],
        'icon60' => ['keywords' => ['peach'], 'nutrition_category' => 'vegetables'],
        'icon61' => ['keywords' => ['rice', 'porridge'], 'nutrition_category' => 'grains'],
        'icon62' => ['keywords' => ['cream', 'soup'], 'nutrition_category' => 'dairy'],
        'icon63' => ['keywords' => ['cream', 'dip'], 'nutrition_category' => 'dairy'],
        'icon64' => ['keywords' => ['baked', 'potato'], 'nutrition_category' => 'grains'],
        'icon65' => ['keywords' => ['herb'], 'nutrition_category' => 'vegetables'],
        'icon67' => ['keywords' => ['corn'], 'nutrition_category' => 'vegetables'],
        'icon68' => ['keywords' => ['potato', 'sweet'], 'nutrition_category' => 'grains'],
        'icon69' => ['keywords' => ['persimmon'], 'nutrition_category' => 'other_extras'],
        'icon70' => ['keywords' => ['pumpkin'], 'nutrition_category' => 'vegetables'],
        'icon71' => ['keywords' => ['chicken', 'soup'], 'nutrition_category' => 'protein'],
        'icon72' => ['keywords' => ['mixed', 'salad'], 'nutrition_category' => 'other_extras'],
        'icon73' => ['keywords' => ['stew', 'chilli', 'soup'], 'nutrition_category' => 'other_extras'],
        'icon74' => ['keywords' => ['lobster'], 'nutrition_category' => 'other_extras'],
        'icon75' => ['keywords' => ['sushi'], 'nutrition_category' => 'other_extras'],
        'icon76' => ['keywords' => ['cake'], 'nutrition_category' => 'other_extras'],
        'icon77' => ['keywords' => ['tempura'], 'nutrition_category' => 'other_extras'],
        'icon78' => ['keywords' => [], 'nutrition_category' => 'other_extras'],
        'icon79' => ['keywords' => ['cabbage'], 'nutrition_category' => 'vegetables'],
        'icon80' => ['keywords' => ['onion', 'scallion'], 'nutrition_category' => 'vegetables'],
        'icon81' => ['keywords' => ['chili'], 'nutrition_category' => 'vegetables'],
        'icon82' => ['keywords' => ['sweet', 'potato'], 'nutrition_category' => 'grains'],
        'icon83' => ['keywords' => ['bread'], 'nutrition_category' => 'grains'],
        'icon84' => ['keywords' => ['sliced', 'deli', 'meat'], 'nutrition_category' => 'protein'],
        'icon85' => ['keywords' => ['carrot', 'cake'], 'nutrition_category' => 'vegetables'],
        'icon86' => ['keywords' => ['strawberry', 'shortcake'], 'nutrition_category' => 'fruit'],
        'icon87' => ['keywords' => ['chocolate', 'pie'], 'nutrition_category' => 'other_extras'],
        'icon88' => ['keywords' => ['pie'], 'nutrition_category' => 'other_extras'],
        'icon89' => ['keywords' => ['chocolate', 'chip', 'cookie'], 'nutrition_category' => 'other_extras'],
        'icon90' => ['keywords' => ['cucumber'], 'nutrition_category' => 'vegetables'],
        'icon91' => ['keywords' => ['cabbage'], 'nutrition_category' => 'vegetables'],
        'icon92' => ['keywords' => ['lettuce'], 'nutrition_category' => 'vegetables'],
        'icon93' => ['keywords' => ['broccoli'], 'nutrition_category' => 'vegetables'],
        'icon94' => ['keywords' => ['radish'], 'nutrition_category' => 'vegetables'],
        'icon95' => ['keywords' => ['grapes'], 'nutrition_category' => 'fruit'],
        'icon96' => ['keywords' => ['garlic'], 'nutrition_category' => 'vegetables'],
        'icon97' => ['keywords' => ['lime'], 'nutrition_category' => 'fruit'],
        'icon98' => ['keywords' => ['eggplant'], 'nutrition_category' => 'protein'],
        'icon99' => ['keywords' => ['cinnamon'], 'nutrition_category' => 'grains'],
        'icon100' => ['keywords' => ['pumpkin', 'pie'], 'nutrition_category' => 'vegetables'],
        'icon101' => ['keywords' => ['meat'], 'nutrition_category' => 'protein'],
        'icon102' => ['keywords' => ['brownie'], 'nutrition_category' => 'other_extras'],
        'icon103' => ['keywords' => ['pretzel'], 'nutrition_category' => 'other_extras'],
        'icon104' => ['keywords' => ['donut'], 'nutrition_category' => 'other_extras'],
        'icon105' => ['keywords' => ['bread'], 'nutrition_category' => 'grains'],
        'icon106' => ['keywords' => ['croissant'], 'nutrition_category' => 'other_extras'],
        'icon107' => ['keywords' => ['ice', 'cream', 'cone'], 'nutrition_category' => 'dairy'],
        'icon108' => ['keywords' => ['chocolate'], 'nutrition_category' => 'other_extras'],
        'icon109' => ['keywords' => ['serve'], 'nutrition_category' => 'other_extras'],
        'icon111' => ['keywords' => ['apple', 'cherry'], 'nutrition_category' => 'fruit'],
        'icon112' => ['keywords' => ['cherry'], 'nutrition_category' => 'fruit'],
        'icon113' => ['keywords' => ['banana'], 'nutrition_category' => 'fruit'],
        'icon114' => ['keywords' => ['lemon'], 'nutrition_category' => 'fruit'],
        'icon115' => ['keywords' => ['chocolate', 'bun'], 'nutrition_category' => 'grains'],
        'icon116' => ['keywords' => ['pretzel', 'bread'], 'nutrition_category' => 'grains'],
        'icon117' => ['keywords' => ['chocolate', 'donut'], 'nutrition_category' => 'other_extras'],
        'icon118' => ['keywords' => ['waffle', 'croffle'], 'nutrition_category' => 'grains'],
        'icon119' => ['keywords' => ['cupcake'], 'nutrition_category' => 'other_extras'],
        'icon120' => ['keywords' => ['birthday', 'cake'], 'nutrition_category' => 'other_extras'],
        'icon121' => ['keywords' => ['peach'], 'nutrition_category' => 'vegetables'],
        'icon122' => ['keywords' => ['pineapple'], 'nutrition_category' => 'fruit'],
        'icon123' => ['keywords' => ['dragonfruit'], 'nutrition_category' => 'fruit'],
        'icon124' => ['keywords' => ['pomegranate', 'apple'], 'nutrition_category' => 'fruit'],
        'icon125' => ['keywords' => ['pear'], 'nutrition_category' => 'vegetables'],
        'icon126' => ['keywords' => ['coffee', 'bean'], 'nutrition_category' => 'protein'],
        'icon127' => ['keywords' => ['white-cap', 'mushroom'], 'nutrition_category' => 'vegetables'],
        'icon128' => ['keywords' => ['red-spotted', 'mushroom'], 'nutrition_category' => 'vegetables'],
        'icon129' => ['keywords' => ['brown-cap', 'mushroom'], 'nutrition_category' => 'vegetables'],
        'icon130' => ['keywords' => ['flower', 'herb', 'bloom'], 'nutrition_category' => 'vegetables'],
        'icon131' => ['keywords' => ['truffle'], 'nutrition_category' => 'other_extras'],
        'icon133' => ['keywords' => ['grapes'], 'nutrition_category' => 'fruit'],
        'icon134' => ['keywords' => ['raspberry'], 'nutrition_category' => 'fruit'],
        'icon135' => ['keywords' => ['strawberry'], 'nutrition_category' => 'fruit'],
        'icon136' => ['keywords' => ['watermelon'], 'nutrition_category' => 'fruit'],
        'icon137' => ['keywords' => ['tea', 'leaf'], 'nutrition_category' => 'other_extras'],
        'icon138' => ['keywords' => ['asparagus'], 'nutrition_category' => 'vegetables'],
        'icon140' => ['keywords' => ['ginger', 'root'], 'nutrition_category' => 'other_extras'],
        'icon141' => ['keywords' => ['herb'], 'nutrition_category' => 'vegetables'],
        'icon142' => ['keywords' => ['lavender'], 'nutrition_category' => 'other_extras'],
        'icon143' => ['keywords' => ['latte', 'tea'], 'nutrition_category' => 'other_extras'],
        'icon144' => ['keywords' => ['matcha', 'tea'], 'nutrition_category' => 'other_extras'],
        'icon145' => ['keywords' => ['coffee'], 'nutrition_category' => 'other_extras'],
        'icon146' => ['keywords' => ['chocolate'], 'nutrition_category' => 'other_extras'],
        'icon147' => ['keywords' => ['soda', 'coke', 'coca', 'cola'], 'nutrition_category' => 'other_extras'],
        'icon148' => ['keywords' => ['beer'], 'nutrition_category' => 'other_extras'],
        'icon149' => ['keywords' => ['martini', 'wine'], 'nutrition_category' => 'other_extras'],
        'icon150' => ['keywords' => ['beer', 'honey'], 'nutrition_category' => 'other_extras'],
        'icon151' => ['keywords' => ['herb', 'kelp'], 'nutrition_category' => 'vegetables'],
        'icon152' => ['keywords' => ['seaweed'], 'nutrition_category' => 'other_extras'],
        'icon153' => ['keywords' => ['honeycomb'], 'nutrition_category' => 'other_extras'],
        'icon154' => ['keywords' => ['blackberries'], 'nutrition_category' => 'fruit'],
        'icon155' => ['keywords' => ['coffee'], 'nutrition_category' => 'other_extras'],
        'icon156' => ['keywords' => ['coffee'], 'nutrition_category' => 'other_extras'],
        'icon157' => ['keywords' => [], 'nutrition_category' => 'other_extras'],
        'icon158' => ['keywords' => ['wine'], 'nutrition_category' => 'other_extras'],
        'icon159' => ['keywords' => ['mussel', 'shell'], 'nutrition_category' => 'protein'],
        'icon160' => ['keywords' => ['oyster', 'shell'], 'nutrition_category' => 'protein'],
        'icon161' => ['keywords' => ['shrimp'], 'nutrition_category' => 'protein'],
        'icon162' => ['keywords' => ['shrimp'], 'nutrition_category' => 'protein'],
    ];
}
